---
- name: Update and upgrade packages
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600 # One hour

- name: Install required common packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ required_apt_packages }}"

- name: Refresh Snap
  ansible.builtin.shell: |
    snap refresh
  
- name: Install Snap packages
  community.general.snap:
    name: "{{ item }}"
    classic: true
  with_items: "{{ required_snap_packages }}"

- name: Install docker requirements
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ required_packages_for_docker }}"

- name: Install docker apt repository key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker apt repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 ] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install required docker packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ docker_packages }}"

- name: Start and enable services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ enabled_started_services }}"